export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SHEETS_SUCCESS = 'LOAD_SHEETS_SUCCESS';
export const UPDATE_SHEET_SUCCESS = 'UPDATE_SHEET_SUCCESS';
export const CREATE_SHEET_SUCCESS = 'CREATE_SHEET_SUCCESS';

export const LOAD_FORCES_SUCCESS = 'LOAD_FORCES_SUCCESS';
export const UPDATE_FORCE_SUCCESS = 'UPDATE_FORCE_SUCCESS';
export const CREATE_FORCE_SUCCESS = 'CREATE_FORCE_SUCCESS';