export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_SHEETS_SUCCESS = 'LOAD_SHEETS_SUCCESS';
export const UPDATE_SHEET_SUCCESS = 'UPDATE_SHEET_SUCCESS';
export const CREATE_SHEET_SUCCESS = 'CREATE_SHEET_SUCCESS';

export const LOAD_FORCES_SUCCESS = 'LOAD_FORCES_SUCCESS';